"""refactor user model to use org_unit_job_position

Revision ID: 7522211ea447
Revises: 55fd18a34dc7
Create Date: 2026-03-02 14:31:33.355840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7522211ea447'
down_revision = '55fd18a34dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit_type', sa.String(length=30), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_unit_job_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_unit_id', sa.Integer(), nullable=False),
    sa.Column('job_position_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_position.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_unit_id', 'job_position_id', name='uq_orgunit_jobpos')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('org_unit_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('org_unit_job_position_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'org_unit', ['org_unit_id'], ['id'])
        batch_op.create_foreign_key(None, 'org_unit_job_position', ['org_unit_job_position_id'], ['id'])
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('org_unit_job_position_id')
        batch_op.drop_column('org_unit_id')
        batch_op.drop_column('job_title')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('gender')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.drop_table('org_unit_job_position')
    op.drop_table('org_unit')
    op.drop_table('job_position')
    # ### end Alembic commands ###
