"""refactor user model to use org_unit_job_position

Revision ID: 800f35ee0e31
Revises: 7522211ea447
Create Date: 2026-03-02 14:34:19.186699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '800f35ee0e31'
down_revision = '7522211ea447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
