"""refactor user model to use org_unit_job_position

Revision ID: 8fcd5ac24b2f
Revises: 06589c298251
Create Date: 2026-03-02 14:49:21.085294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fcd5ac24b2f'
down_revision = '06589c298251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('org_unit_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('org_unit_job_position_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('org_unit_job_position_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('org_unit_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
