"""update org_unit relations and defaults

Revision ID: bcdb86078906
Revises: 8fcd5ac24b2f
Create Date: 2026-03-04 08:46:01.971864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcdb86078906'
down_revision = '8fcd5ac24b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_unit', schema=None) as batch_op:
        batch_op.alter_column('unit_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_org_unit_parent_id'), ['parent_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    with op.batch_alter_table('org_unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_unit_parent_id'))
        batch_op.alter_column('unit_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=True)

    # ### end Alembic commands ###
