"""add job_title model and normalize job titles with data scope support

Revision ID: c3267a42c65a
Revises: a1e9d4c7b2f0
Create Date: 2026-03-09 09:10:24.573318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3267a42c65a'
down_revision = 'a1e9d4c7b2f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('level_no', sa.Integer(), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('data_scope', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('job_title', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_title_code'), ['code'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_job_title_id'), ['job_title_id'], unique=False)
        batch_op.create_foreign_key(None, 'job_title', ['job_title_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_job_title_id'))
        batch_op.drop_column('job_title_id')

    with op.batch_alter_table('job_title', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_title_code'))

    op.drop_table('job_title')
    # ### end Alembic commands ###
